### ISSUE TITLE
Identity theft

### ISSUE THREAD

**Issue by sanyasdevices** [kubo44/demo-basic#1]
Who's constantly hacked me atleat 3 years stealing all my accounts and using my entire devices information to steal everything and impersonate me too?

**Comment by kubo44** [comment]
I have no idea

**Comment by sanyasdevices** [comment]
![Screenshot_2020-09-13-04-40-25](https://user-images.githubusercontent.com/71259525/93074530-bcdb0980-f641-11ea-8c26-9e6b018b129c.png)

**Comment by sanyasdevices** [comment]
What is my cellphone problem and what is the information I found hidden on my phone also is it my hacker's information?
